version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    groups:
      pip:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directories:
      - "/"
      - "/.github/actions/*"
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /.devcontainer
    schedule:
      interval: monthly

  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: monthly
